name: Linters

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:'~>1.7' 
          [ -f .rubocop.yml ] || .rubocop.yml
      - name: Rubocop Report
        run: rubocop --color
